const listData = [
    {
        id: 1,
        name: "Zinger Burger",
        price: 199,
        image: "https://tse2.mm.bing.net/th/id/OIP.uYLZRXytpaJr-QyFW1QHEwHaEo?rs=1&pid=ImgDetMain",
        description: "Crispy chicken fillet with lettuce and mayo in a sesame bun.",
        star: 4.5,
        cost: "Medium",
        deliveryTime: "30 mins",
        cuisines: ["American", "Fast Food", "Chicken"],
      },
      {
        id: 2,
        name: "Zinger Tower Burger",
        price: 249,
        image: "https://tse3.mm.bing.net/th/id/OIP.2dhr5Ln6cMHIu9SmwE_uBgHaE7?rs=1&pid=ImgDetMain",
        description: "Zinger burger with added cheese and hash brown for extra crunch.",
        star: 3.7,
        cost: "High",
        deliveryTime: "35 mins",
        cuisines: ["American", "Fast Food", "Chicken"],
      },
      {
        id: 3,
        name: "Chicken Bucket (4 pcs)",
        price: 499,
        image: "https://tse2.mm.bing.net/th/id/OIP.uYLZRXytpaJr-QyFW1QHEwHaEo?rs=1&pid=ImgDetMain",
        description: "4 pieces of crispy fried chicken, perfect for sharing.",
        star: 4.6,
        cost: "High",
        deliveryTime: "40 mins",
        cuisines: ["American", "Fast Food", "Crispy Chicken"],
      },
      {
        id: 4,
        name: "Ultimate Savings Bucket",
        price: 799,
        image: "https://tse2.mm.bing.net/th/id/OIP.zqg_ZZsg8VZuLLsCsldABwHaFJ?rs=1&pid=ImgDetMain",
        description: "10 pcs of chicken, fries, and dips.",
        star: 3.8,
        cost: "Very High",
        deliveryTime: "45 mins",
        cuisines: ["American", "Fast Food", "Crispy Chicken"],
      },
      {
        id: 5,
        name: "Hot Wings (6 pcs)",
        price: 249,
        image: "https://tse2.mm.bing.net/th/id/OIP.zqg_ZZsg8VZuLLsCsldABwHaFJ?rs=1&pid=ImgDetMain",
        description: "Spicy and crispy hot wings, great for snacking.",
        star: 4.4,
        cost: "Medium",
        deliveryTime: "25 mins",
        cuisines: ["American", "Spicy", "Chicken"],
      },
      {
        id: 6,
        name: "Popcorn Chicken",
        price: 199,
        image: "https://fastfoodcity.com/wp-content/uploads/fast-food-fastfoodcity.com-003.jpg",
        description: "Bite-sized crispy chicken pieces, served with a dip.",
        star: 3.3,
        cost: "Low",
        deliveryTime: "20 mins",
        cuisines: ["American", "Fast Food", "Bite-Sized"],
      },
      {
        id: 7,
        name: "Pepsi (500ml)",
        price: 59,
        image: "https://theword360.com/wp-content/uploads/2020/09/maxresdefault.jpg",
        description: "Chilled refreshing Pepsi.",
        star: 4.2,
        cost: "Low",
        deliveryTime: "10 mins",
        cuisines: ["Beverage", "Soft Drink"],
      },
  ];  

export default listData;